### PR TITLE
Updating Files to-date

### PR DESCRIPTION
**Pull request by singhaditya28**
I noticed that we had problems updating the .gitignore file and requirements.txt. I have thoroughly updated both of them. 

Hope it Helps! :smile: 👍

### CODE REVIEW

**Review by david-berthelot — COMMENTED** [review]
1. where is requests used?
2. What is the "lmbd" dependency you added? We use "lmdb".
3. I don't see the point of updating the .gitignore file since this isn't a project meant to receive commit, instead it's a meant to be snapshot of the code used for the LAG paper.

**Comment by singhaditya28** [comment]
Alright @david-berthelot ,
Have update all the files as per your concern.
On .gitignore file, we should update the file as it increases security and isolates private files/records from being accessible.
Hope I can help you. 😃

**Review by david-berthelot — CHANGES_REQUESTED** [review]
It seems your changes to requirements.txt are only empty lines. Can you clean this up?
Thanks.

**Comment by singhaditya28** [comment]
Done ! @david-berthelot !
Thanks for the review 😃

**Review by david-berthelot — APPROVED** [review]
Thanks!

**Pull request merged**
